experiment_name: "seg_100_10_timeline_0.7"

mini_batch:
  size: 8
  # N for divide batch into N mini-batches
  # -1 for don't use mini batch

data:
  source: "youtube" # "opensource"
  opensource: "ccdv/govreport-summarization"
  youtube: "WhiteboardLLM/Data"
  index_set: 4

segment:
  args:
    n_word: 100
    n_overlap: 0
    fix_size: False

concat:
  method: "concate_time_based"
  args:
    threshold: 0.6

summary:
  args:
    min_length: 100
    max_length: 1024